//! MBTiles 1.3 sink (SQLite).
//!
//! Tiles are stored in the TMS scheme as the spec requires: the XYZ row is
//! flipped via [`TileCoord::tms_row`] on insert.

use std::path::Path;

use rusqlite::{Connection, params};

use crate::error::Result;
use crate::mercator::TileCoord;
use crate::pyramid::{PyramidMetadata, TileSink};

/// Streaming MBTiles writer. All inserts run inside a single transaction
/// that is committed by [`TileSink::finalize`].
#[derive(Debug)]
pub struct MbtilesSink {
    conn: Connection,
}

impl MbtilesSink {
    /// Create (or overwrite) an MBTiles file.
    pub fn create(path: impl AsRef<Path>) -> Result<Self> {
        let path = path.as_ref();
        // A stale file would make CREATE TABLE fail or mix tile sets.
        if path.exists() {
            std::fs::remove_file(path).map_err(|source| crate::error::Error::Io {
                path: path.to_path_buf(),
                source,
            })?;
        }
        let conn = Connection::open(path)?;
        // Bulk-load settings: the file is rebuilt from scratch on failure,
        // so durability mid-write buys nothing.
        conn.execute_batch(
            "PRAGMA journal_mode = OFF;
             PRAGMA synchronous = OFF;
             CREATE TABLE metadata (name TEXT, value TEXT);
             CREATE TABLE tiles (
                 zoom_level INTEGER,
                 tile_column INTEGER,
                 tile_row INTEGER,
                 tile_data BLOB
             );
             CREATE UNIQUE INDEX tile_index
                 ON tiles (zoom_level, tile_column, tile_row);
             BEGIN;",
        )?;
        Ok(Self { conn })
    }
}

impl TileSink for MbtilesSink {
    fn put(&mut self, coord: TileCoord, png: &[u8]) -> Result<()> {
        self.conn
            .prepare_cached(
                "INSERT INTO tiles (zoom_level, tile_column, tile_row, tile_data)
                 VALUES (?1, ?2, ?3, ?4)",
            )?
            .execute(params![coord.z, coord.x, coord.tms_row(), png])?;
        Ok(())
    }

    fn finalize(&mut self, meta: &PyramidMetadata) -> Result<()> {
        let (w, s, e, n) = meta.bounds_lonlat;
        let center = format!("{},{},{}", (w + e) / 2.0, (s + n) / 2.0, meta.min_zoom);
        let rows: &[(&str, String)] = &[
            ("name", meta.name.clone()),
            ("format", meta.format.to_string()),
            ("bounds", format!("{w},{s},{e},{n}")),
            ("center", center),
            ("minzoom", meta.min_zoom.to_string()),
            ("maxzoom", meta.max_zoom.to_string()),
            ("type", "overlay".to_string()),
            ("version", "1".to_string()),
            ("description", "Generated by geotiles".to_string()),
        ];
        {
            let mut stmt = self
                .conn
                .prepare("INSERT INTO metadata (name, value) VALUES (?1, ?2)")?;
            for (k, v) in rows {
                stmt.execute(params![k, v])?;
            }
        }
        self.conn.execute_batch("COMMIT;")?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn writes_spec_compliant_mbtiles() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("out.mbtiles");

        let mut sink = MbtilesSink::create(&path).unwrap();
        // XYZ (z1, x0, y0) is the NW quadrant → TMS row 1.
        sink.put(TileCoord { z: 1, x: 0, y: 0 }, b"png-bytes").unwrap();
        sink.finalize(&PyramidMetadata {
            name: "dem".into(),
            bounds_lonlat: (-72.0, -34.0, -70.0, -32.0),
            min_zoom: 0,
            max_zoom: 1,
            format: "png",
        })
        .unwrap();
        drop(sink);

        let conn = Connection::open(&path).unwrap();
        let row: u32 = conn
            .query_row(
                "SELECT tile_row FROM tiles WHERE zoom_level = 1 AND tile_column = 0",
                [],
                |r| r.get(0),
            )
            .unwrap();
        assert_eq!(row, 1, "XYZ y=0 must be stored as TMS row 1 at z1");

        let format: String = conn
            .query_row("SELECT value FROM metadata WHERE name = 'format'", [], |r| r.get(0))
            .unwrap();
        assert_eq!(format, "png");
        let bounds: String = conn
            .query_row("SELECT value FROM metadata WHERE name = 'bounds'", [], |r| r.get(0))
            .unwrap();
        assert_eq!(bounds, "-72,-34,-70,-32");
    }

    #[test]
    fn create_overwrites_existing_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("out.mbtiles");
        std::fs::write(&path, b"garbage").unwrap();
        let mut sink = MbtilesSink::create(&path).unwrap();
        sink.finalize(&PyramidMetadata {
            name: "empty".into(),
            bounds_lonlat: (0.0, 0.0, 1.0, 1.0),
            min_zoom: 0,
            max_zoom: 0,
            format: "png",
        })
        .unwrap();
    }
}
